#!/bin/bash
TMPBG=/tmp/screen.png
RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')
ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -filter_complex "boxblur=7:1,drawtext=fontfile=/usr/share/fonts/TTF/UbuntuMono-Bold.ttf:text='Silex':fontcolor='#ffffffe0':fontsize=75:x=(((w/2)-tw)/2)+(w-tw)/2:y=(h-th)/2:shadowcolor='#1d1f21d0':shadowx=2:shadowy=2:" -vframes 1 $TMPBG -loglevel quiet
i3lock -i $TMPBG
rm $TMPBG
